routes/web.php
<?php

use App\Http\Controllers\QuotationController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\VideoController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RMAController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\HelpSupportController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('login');
// Auth::routes();

Route::get('/success', function () {
    return view('auth.success');
})->name('success');

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {

    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');

    Route::get('/go_back', [App\Http\Controllers\UserController::class, 'go_back'])->name('go_back');
    // Route::get('/go_back_product', [App\Http\Controllers\ProductController::class, 'go_back_product'])->name('go_back_product');

    Route::get('/profile', [App\Http\Controllers\UserController::class, 'profile'])->name('profile');
    // Route::get('/p_profile', [App\Http\Controllers\ProductController::class, 'p_profile'])->name('p_profile');

    Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'dashboard'])->name('dashboard');

    Route::post('/profilesql', [App\Http\Controllers\UserController::class, 'profilesql'])->name('profilesql');
    // Route::post('/p_profilesql', [App\Http\Controllers\ProductController::class, 'p_profilesql'])->name('p_profilesql');

    Route::get('forget-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');


    Route::post('forget-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
    Route::get('reset-password/{token}', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
    Route::post('reset-password-post', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

    Route::get('/delete_user/{id}', [UserController::class, 'destroy']);
    Route::get('/delete_user/{id}', [UserController::class, 'destroy']);

    Route::get('change-password', [App\Http\Controllers\ChangePasswordController::class, 'index']);
    Route::post('change-password', [App\Http\Controllers\ChangePasswordController::class, 'store'])->name('change.password');


    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('rmas', RMAController::class);
    Route::resource('quotation', QuotationController::class);
    
    
    Route::resource('announcement', AnnouncementController::class);
    Route::post('updatedata/{announcement}', [AnnouncementController::class, 'updatedata'])->name('updatedata');
    Route::get('delete_announcement/{id}', [AnnouncementController::class, 'delete_announcement'])->name('delete_announcement');

    Route::get('video/index', [VideoController::class, 'index'])->name('video.index');
    Route::get('video/create', [VideoController::class, 'create'])->name('video.create');
    Route::get('video/uploadvideofile', [VideoController::class, 'uploadvideofile'])->name('video.uploadvideofile');
    Route::post('video/store', [VideoController::class, 'store'])->name('video.store');
    Route::post('video/uploadfile', [VideoController::class, 'uploadfile'])->name('video.uploadfile');
    Route::get('video/edit/{id}', [VideoController::class, 'edit'])->name('video.edit');
    Route::post('video/update/{id}', [VideoController::class, 'update'])->name('video.update');
    Route::get('video/delete/{id}', [VideoController::class, 'destroy'])->name('video.delete');
    Route::get('video/show/{id}', [VideoController::class, 'show'])->name('video.show');
    
    
    Route::resource('orders', OrderController::class);
    Route::resource('changePassword', ChangePasswordController::class);
    Route::resource('helpSupport', HelpSupportController::class);

    Route::resource('rating', App\Http\Controllers\RatingController::class);
	Route::resource('faqs', App\Http\Controllers\FAQsController::class);
	Route::resource('feedback', App\Http\Controllers\FeedbackController::class);
	Route::resource('cms', App\Http\Controllers\CMSPagesController::class);

	Route::get('reports/orders','App\Http\Controllers\ReportsController@orders')->name('reports.orders');
	Route::get('reports/products','App\Http\Controllers\ReportsController@products')->name('reports.products');
	Route::get('reports/rmas','App\Http\Controllers\ReportsController@rmas')->name('reports.rmas');

	Route::post('rmas/edit_status','App\Http\Controllers\RMAController@edit_status')->name('rmas.rmas');
    Route::get('faq/delete/{id}','App\Http\Controllers\FAQsController@delete')->name('faq.delete');
    Route::get('cms_page/delete/{id}','App\Http\Controllers\CMSPagesController@delete')->name('cms_page.delete');
  
  /* Notification */
    Route::get('user_notification','App\Http\Controllers\NotificationController@index')->name('notification.index');
    Route::get('create-notification','App\Http\Controllers\NotificationController@create')->name('notification.create');
    Route::post('store-notification','App\Http\Controllers\NotificationController@storeNotification')->name('notification.storeNotification');
    /*End Notification*/  
    
    Route::get('order/export','App\Http\Controllers\ReportsController@orderexport')->name('order.export');
    Route::get('product/export','App\Http\Controllers\ReportsController@productexport')->name('product.export');
    Route::get('rma/export','App\Http\Controllers\ReportsController@rmaexport')->name('rma.export');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Announcement.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Announcement extends Model
{
    use HasFactory;
    protected $table = 'announcements';

    protected $fillable = [
        'id',
        'url',
        'image',
        'title',
        'description',
        'status'
    ];


}

app/Http/Controllers/AnnouncementController.php
<?php

namespace App\Http\Controllers;
use App\Models\Announcement;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Carbon\Carbon;


class AnnouncementController extends Controller
{
    public function index(Request $request)
    {
        
        if ($request->ajax()) {
            $data = Announcement::where('status','0')->get();
            return Datatables::of($data)
            ->addIndexColumn()
            ->filter(function ($instance) use ($request) {                  
                   if ($request->input('search.value') != "") {
                         return $instance->where('title','like','%'.$request->input('search.value').'%');
                        }                                      
                    })
                    ->editColumn('created_at', function ($row){
                        return Carbon::parse($row->created_at)->format('d-m-Y H:i:s');
                    })
                    ->editColumn('url', function ($row){
                      return "<a href='$row->url' target='_blank'/> $row->url </a>";
                     })
                    ->editColumn('image', function ($row){
                          $pics = asset($row->image);
                        return "<img src=' $pics ' max-width='150' height='80' />";
                    })
               
                    ->addColumn('action', function ($row) {
                        $btn = '<a href="' . route('announcement.show',$row->id) . '" ><i class="zmdi zmdi-eye" style="color:green; margin-left:10px; "></i></a>
                                <a href="' . route('announcement.edit',$row->id) . '" ><i class="zmdi zmdi-edit" style="color:blue;  margin-left:10px;"></i></a>
                                <a href="#" class="remove" data-id="'.$row->id.'"><i class="zmdi zmdi-delete" style="color:red;  margin-left:10px;"></i></a>';
                            return $btn;
                    })
                    ->rawColumns(['action','created_at','image','url'])
                    ->make(true);
        }
        return view('admin.announcement.index');
    }

    public function create()
    {
        return view('admin.announcement.create');
    }

    public function store(Request $request)
    {
       $request->validate([
            'title' => 'required',
            'description' =>'required',
            'url' => 'required|url',
        ]);
        
        if($request->hasFile('image')){
            $image = $request->file('image');
            $image_name = $image->getClientOriginalName();
            $image->move(public_path('/images'),$image_name);        
            $image_path = "/images/" . $image_name;
        }else{
            $request->validate([
                    'image' => 'required'
                ]);
        }

        Announcement::create([
            'title' => $request->title,
            'description' =>$request->description,
            'url' => $request->url,
            'image' => $image_path,
            'created_at' => now(),
            'updated_at' => null
        ]);
       
        return redirect()->route('announcement.index')->with('success', 'Announcement created successfully.');
    
    }

    public function show($id)
    {
        $data = Announcement::find($id);
        return view("admin.announcement.show",['data' => $data]);
    }

    public function edit($id)
    {
        $data = Announcement::find($id);
        return view("admin.announcement.edit",['data' => $data]);
    }

    public function updatedata(Request $request,Announcement $announcement)
    {
        $request->validate([
            'title' => 'required',
            'description' =>'required',
            'url' => 'required|url',
        ]);

        if($request->hasFile('image')){
            $image = $request->file('image');
            $image_name = $image->getClientOriginalName();
            $image->move(public_path('/images'),$image_name);        
            $image_path = "/images/" . $image_name;
        }

        $announcement->title = $request->title;
        $announcement->url = $request->url;
        $announcement->description = $request->description;
        if($request->image){
            $announcement->image = $image_path;
        }else{
            
        }
        $announcement->save();

        return redirect()->route('announcement.index')->with('success', 'Announcement Updated successfully.');
    }

    public function delete_announcement($id)
    {
        Announcement::where('id',$id)->delete();
        // Alert::warning('Warning Title', 'Warning Message');
        return redirect()->route('announcement.index')->with('success', 'Announcement Deleted successfully.');

    }
}

resources/views/admin/announcement/create.blade.php
@extends('admin.layout')

@section('content')
    <div class="block-header">
    <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>New Announcement</h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="zmdi zmdi-home"></i> Home</a></li>
                    <li class="breadcrumb-item active">Add Announcement</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                    <ul class="header-dropdown m-r--5">
                            <a href="{{route('go_back')}}"><i class="zmdi zmdi-arrow-left"></i></a>
                    </ul><br>
                        @if (count($errors) > 0)
                      <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                           @foreach ($errors->all() as $error)
                             <li>{{ $error }}</li>
                           @endforeach
                        </ul>
                      </div>
                    @endif
                    </div>
                    <div class="body">
                        <form action="{{ route('announcement.store') }}" id="myform" method="POST" enctype="multipart/form-data" runat="server">
                            @csrf
                            <div class="row">
                                <div class="col-sm-12">
                                    <label for="name">Title</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="title" name="title" class="form-control" placeholder="Enter Title">
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <label for="name">Description</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <textarea id="description" name="description" class="form-control" placeholder="Enter Description" row="3"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>


                          
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="name">URL</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="url" name="url" class="form-control" placeholder="Enter URL">
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-6">
                                    <label for="Image">Picture</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input id="uploadImage" type="file" name="image"  class="form-control hidden" onchange="PreviewImage();" accept=".png, .jpg, .jpeg" />
                                            <label for="uploadImage" class="btn btn-secondary">Click Me To Image</label>                          
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                      <div class="form-group">
                                        <img src="#" id="uploadPreview" style="width: 180px; height: 110px;" />
                                      </div>
                                </div>    
                            </div>
                            
                          
                          <div class="row">
                          <div class="col-md-6">
                                    <div class="form-group">
                                    <button type="submit" class="btn btn-raised btn-primary waves-effect">Create</button>
                                    </div>
                                </div>
                          </div>
                        </form>
                    </div>
                </div>
            </div>
        </div> 
    </div>  
        
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.2/jquery.form.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script type="text/javascript">
 $("#uploadPreview").hide();
    function PreviewImage() {
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("uploadImage").files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById("uploadPreview").src = oFREvent.target.result;
        };
        $("#uploadPreview").show();
    };


    $( "#myform" ).validate({
          rules: {
            title: {
              required: true,
              minlength: 2,
              maxlength: 20
            },
            description: {
              required: true,
              minlength: 10,
              maxlength: 200
            },
            url: {
              required: true,
            },
            image:{
                required:true,
                  extension: 'png|jpg|jpeg',
            }
            
          },
          messages: {
            title: {
              required: "Please Enter a Title",
            },
            description: {
              required: "Please Enter a Description",
            },
            url: {
              required: "Please Enter a URL",
            },
            image:{
                 required: "Please Enter a Image",
            }
            
          }
        });
    </script>
    
@endsection     

resources/views/admin/announcement/edit.blade.php
@extends('admin.layout')

@section('content')
    <div class="block-header">
    <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Edit Announcement</h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="zmdi zmdi-home"></i> Home</a></li>
                    <li class="breadcrumb-item active">Edit Announcement</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        @if (count($errors) > 0)
                      <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                           @foreach ($errors->all() as $error)
                             <li>{{ $error }}</li>
                           @endforeach
                        </ul>
                      </div>
                    @endif
                    <ul class="header-dropdown m-r--5">
                            <a href="{{route('go_back')}}"><i class="zmdi zmdi-arrow-left"></i></a>
                    </ul><br>
                    </div>
                    <div class="body">
                        <form action="{{ route('updatedata',[$data->id]) }}" id="myform" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-sm-12">
                                    <label for="name">Title</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="title" name="title" class="form-control" value="{{ $data->title }} " placeholder="Enter Title" >
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <label for="name">Description</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <textarea id="description" name="description" class="form-control" placeholder="Enter Description" row="3">{{ $data->description }} </textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <label for="name">URL</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="url" name="url" class="form-control" value="{{ $data->url }} " placeholder="Enter URL">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <label for="Image">Picture</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                        <input id="uploadImage" type="file" name="image"  class="form-control hidden" onchange="PreviewImage();" accept=".png, .jpg, .jpeg" />
                                            <label for="uploadImage" class="btn btn-secondary">Click Me To Update Image</label>       
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                      <div class="form-group">
                                       <img src='{{ asset($data->image) }}' id="uploadPreview" height='100' />
                                      </div>
                                </div>                                            
                            </div>
                            
                          
                          <div class="row">
                          <div class="col-md-6">
                                    <div class="form-group">
                                    <button type="submit" class="btn btn-raised btn-primary waves-effect">Update</button>
                                    </div>
                                </div>
                          </div>
                        </form>
                    </div>
                </div>
            </div>
        </div> 
    </div>  
    
<script type="text/javascript">

    function PreviewImage() {
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("uploadImage").files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById("uploadPreview").src = oFREvent.target.result;
        };
    };


    $( "#myform" ).validate({
          rules: {
            title: {
              required: true,
              minlength: 2,
              maxlength: 20
            },
            description: {
              required: true,
              minlength: 10,
              maxlength: 500
            },
            url: {
              required: true,
            },
            
          },
          messages: {
            title: {
              required: "Please Enter a Title",
            },
            description: {
              required: "Please Enter a Description",
            },
            url: {
              required: "Please Enter a URL",
            },
            
          }
        });
    </script>
    
@endsection     

resources/views/admin/announcement/index.blade.php
@extends('admin.layout')

@section('content')
    <?php
    $i = 1;
    ?>
    
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Announcements List</h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="zmdi zmdi-home"></i> Home</a>
                    </li>
                    <li class="breadcrumb-item active">Announcements List</li>
                </ul>
            </div>
        </div>
    </div>
    <!--  <button class="btn btn-raised btn-primary waves-effect" data-type="autoclose-timer">CLICK ME</button> -->
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    @if ($message = Session::get('success'))
                        <div class="alert bg-success text-white alert-styled-left alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                            <span class="font-weight-semibold">Well done!</span> {{$message}}.
                        </div>
                    @endif

                    <div class="header">
                        <ul class="header-dropdown m-r--5">
                            <a href="{{route('announcement.create')}}" class="btn btn-raised btn-primary m-t-15 waves-effect">Add Announcement</a>
                        </ul><br>
                    </div>
                
                    <div class="body table-responsive">
                        <table class="table table-bordered table-hover js-basic-example " id="announcement_table">
                        <thead style="background-color:#ededed;">
                            <tr class="text-center">
                                <th>ID</th>
                                <th style="">Image</th>
                                <th>URL</th>
                                <th>Title</th>
                                <th style="width: 300px;">Description</th>
                                <th>Created-At</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://unpkg.com/sweetalert2@7.8.2/dist/sweetalert2.all.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    <script type="text/javascript">
        $(function () {
            setTimeout(function(){
                $(".alert").remove();
            }, 3000 ); 
   
            var table = $('#announcement_table').DataTable({
                responsive: true,
                order:[0,'desc'],
                ajax: "{{ route('announcement.index') }}",
                columns: [
                    { data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: true, searchable: true },
                    {data: 'image', name: 'image', orderable: true, searchable: true},
                    {data: 'url', name: 'url', orderable: false, searchable: false},
                    {data: 'title', name: 'title', orderable: true, searchable: true},
                    {data: 'description', name: 'description', orderable: true, searchable: true},
                    {data: 'created_at', name: 'created_at'},
                    {data: 'action', name: 'action'},
                ]
            });


        $(document).on("click", ".remove", function (e) {
            var id = $(this).data("id");
            var token = $(this).data("token");
            swal.fire({
                title: "Delete Announcement",
                text: "Are You Sure Want to Delete this Announcement?",
                type: "warning",
                showCancelButton: !0,
                confirmButtonText: "Delete!",
                cancelButtonText: "Cancel",
                reverseButtons: !0
            }).then(function (e) {

                if (e.value === true) {
                    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');

                    $.ajax(
                        {
                            url: "{{ url('delete_announcement')}}/"+id,
                            type: 'GET',
                            data: {
                                "id": id,
                                "_token": token,
                            },
                            success: function (response) {
                                if (response.success == true) {
                                    swal.fire("Announcement not delete!!", response.message, "error");
                                    // location.reload();
                                } else {
                                    swal.fire("Announcement Deleted Successfully!", response.message, "success");
                                    location.reload();
                                }
                            }
                        });
                } else {
                    e.dismiss;
                }

            })

        });

           
        });
    </script>
@endsection