routes/web.php
<?php

use App\Http\Controllers\QuotationController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\VideoController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RMAController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\HelpSupportController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
})->name('login');
// Auth::routes();

Route::get('/success', function () {
    return view('auth.success');
})->name('success');

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {

    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');

    Route::get('/go_back', [App\Http\Controllers\UserController::class, 'go_back'])->name('go_back');
    // Route::get('/go_back_product', [App\Http\Controllers\ProductController::class, 'go_back_product'])->name('go_back_product');

    Route::get('/profile', [App\Http\Controllers\UserController::class, 'profile'])->name('profile');
    // Route::get('/p_profile', [App\Http\Controllers\ProductController::class, 'p_profile'])->name('p_profile');

    Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'dashboard'])->name('dashboard');

    Route::post('/profilesql', [App\Http\Controllers\UserController::class, 'profilesql'])->name('profilesql');
    // Route::post('/p_profilesql', [App\Http\Controllers\ProductController::class, 'p_profilesql'])->name('p_profilesql');

    Route::get('forget-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'showForgetPasswordForm'])->name('forget.password.get');


    Route::post('forget-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'submitForgetPasswordForm'])->name('forget.password.post');
    Route::get('reset-password/{token}', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'showResetPasswordForm'])->name('reset.password.get');
    Route::post('reset-password-post', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'submitResetPasswordForm'])->name('reset.password.post');

    Route::get('/delete_user/{id}', [UserController::class, 'destroy']);
    Route::get('/delete_user/{id}', [UserController::class, 'destroy']);

    Route::get('change-password', [App\Http\Controllers\ChangePasswordController::class, 'index']);
    Route::post('change-password', [App\Http\Controllers\ChangePasswordController::class, 'store'])->name('change.password');


    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('rmas', RMAController::class);
    Route::resource('quotation', QuotationController::class);
    
    
    Route::resource('announcement', AnnouncementController::class);
    Route::post('updatedata/{announcement}', [AnnouncementController::class, 'updatedata'])->name('updatedata');
    Route::get('delete_announcement/{id}', [AnnouncementController::class, 'delete_announcement'])->name('delete_announcement');

    Route::get('video/index', [VideoController::class, 'index'])->name('video.index');
    Route::get('video/create', [VideoController::class, 'create'])->name('video.create');
    Route::get('video/uploadvideofile', [VideoController::class, 'uploadvideofile'])->name('video.uploadvideofile');
    Route::post('video/store', [VideoController::class, 'store'])->name('video.store');
    Route::post('video/uploadfile', [VideoController::class, 'uploadfile'])->name('video.uploadfile');
    Route::get('video/edit/{id}', [VideoController::class, 'edit'])->name('video.edit');
    Route::post('video/update/{id}', [VideoController::class, 'update'])->name('video.update');
    Route::get('video/delete/{id}', [VideoController::class, 'destroy'])->name('video.delete');
    Route::get('video/show/{id}', [VideoController::class, 'show'])->name('video.show');
    
    
    Route::resource('orders', OrderController::class);
    Route::resource('changePassword', ChangePasswordController::class);
    Route::resource('helpSupport', HelpSupportController::class);

    Route::resource('rating', App\Http\Controllers\RatingController::class);
	Route::resource('faqs', App\Http\Controllers\FAQsController::class);
	Route::resource('feedback', App\Http\Controllers\FeedbackController::class);
	Route::resource('cms', App\Http\Controllers\CMSPagesController::class);

	Route::get('reports/orders','App\Http\Controllers\ReportsController@orders')->name('reports.orders');
	Route::get('reports/products','App\Http\Controllers\ReportsController@products')->name('reports.products');
	Route::get('reports/rmas','App\Http\Controllers\ReportsController@rmas')->name('reports.rmas');

	Route::post('rmas/edit_status','App\Http\Controllers\RMAController@edit_status')->name('rmas.rmas');
    Route::get('faq/delete/{id}','App\Http\Controllers\FAQsController@delete')->name('faq.delete');
    Route::get('cms_page/delete/{id}','App\Http\Controllers\CMSPagesController@delete')->name('cms_page.delete');
  
  /* Notification */
    Route::get('user_notification','App\Http\Controllers\NotificationController@index')->name('notification.index');
    Route::get('create-notification','App\Http\Controllers\NotificationController@create')->name('notification.create');
    Route::post('store-notification','App\Http\Controllers\NotificationController@storeNotification')->name('notification.storeNotification');
    /*End Notification*/  
    
    Route::get('order/export','App\Http\Controllers\ReportsController@orderexport')->name('order.export');
    Route::get('product/export','App\Http\Controllers\ReportsController@productexport')->name('product.export');
    Route::get('rma/export','App\Http\Controllers\ReportsController@rmaexport')->name('rma.export');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/FAQs.php
<?php


namespace App\Models;


use Illuminate\Database\Eloquent\SoftDeletes;

use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\Model;


class FAQs extends Model

{

    use HasFactory;
    use SoftDeletes;

    protected $table = 'faqs';

    protected $fillable = [
        'title_english',
        'description_english',
        'title_german',
        'description_german'
    ];

    protected $dates = ['deleted_at'];


}

app/Http/Controllers/FAQsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\FAQs;
use DB;
use Hash;
use Illuminate\Support\Arr;
use DataTables;
use Illuminate\Support\Str;


class FAQsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
            
        if ($request->ajax()) { 


            $data = FAQs::select('*'); 

            return Datatables::of($data)
                     ->addIndexColumn()
                     ->addColumn('action', function($row){
                        
                            $btn = '<a href="'.route("faqs.show",$row->id).'"><i class="zmdi zmdi-eye" style="color:green;"></i></a>  &nbsp; 
                                    <a href="'.route("faqs.edit",$row->id).'"><i class="zmdi zmdi-edit" style="color:blue;"></i></a>&nbsp;
				   
				                <a href="'.route("faq.delete",$row->id).'"><i class="zmdi zmdi-delete" style="color:red;"></i></a>&nbsp;
                            ';
       
                             return $btn;
                     })
                     
                    ->editColumn('description_english',function($row){
                         
                         return Str::limit($row->description_english, 50, ' (...)');

                     })
                
                     ->rawColumns(['action'])
                     ->make(true);
         }
         
       
        return view('admin.faqs.index');
    }
    
    public function create()
    {
    
        return view('admin.faqs.create');
    }
    
    
    public function store(Request $request)
    {

        $this->validate($request, [
            'title_english' => 'required',
            'description_english' => 'required',
            'title_german' => 'required',
            'description_german' => 'required',
        ]);

        $input = $request->all();

        FAQs::create($input);

        return redirect()->back()->with('success','Created successfully');
    }

     /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = FAQs::find($id);
        return view('admin.faqs.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'title_english' => 'required',
            'description_english' => 'required',
            'title_german' => 'required',
            'description_german' => 'required',
        ]);

        $input = $request->all();

        $data = FAQs::find($id);
        $data->update($input);

        return redirect()->back()->with('success','Updated successfully');
    }
    
      
    public function delete($id)
    {
    	$data = FAQs::find($id)->delete();
    	return redirect()->back()->with('success','Deleted successfully');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = FAQs::find($id);
        return view('admin.faqs.show',compact('data'));
    }
    
  
}

resources/views/admin/faqs/create.blade.php
@extends('admin.layout')

@section('content')
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Add FAQs</h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="zmdi zmdi-home"></i> Home</a></li>
                    <li class="breadcrumb-item active">Add FAQs</li>
                </ul>
            </div>
        </div>
    </div>
 
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                     @if ($message = Session::get('success'))
                      <div class="alert bg-success text-white alert-styled-left alert-dismissible">
                              <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                              <span class="font-weight-semibold">Well done!</span> {{$message}}.
                              </div>
                      @endif
                    <div class="header">
                        @if (count($errors) > 0)
                      <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                           @foreach ($errors->all() as $error)
                             <li>{{ $error }}</li>
                           @endforeach
                        </ul>
                      </div>
                    @endif
                    <ul class="header-dropdown">
                            
                            <a href="{{url('faqs')}}"><i class="zmdi zmdi-arrow-left"></i></a>
                    </ul><br>
                    </div>
                    <div class="body">
                        <form action="{{ route('faqs.store') }}" id="myform" method="POST" enctype="multipart/form-data" runat="server">
                            @csrf
                          
                           <div class="row">
                            <div class="col-md-12">
                                    <label for="title_english">Title English</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                             <input type="text" id="title_english" name="title_english" class="form-control">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row"> 
                            	<div class="col-md-12">
                                    <label for="description">Detail English</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <textarea type="text" id="description_english" name="description_english" class="form-control" style="height:300px;"></textarea>
                                        </div>
                                    </div>
                                </div>  
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="title_german">Title German</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="title_german" name="title_german" class="form-control">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="description_german">Detail German</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <textarea type="text" id="description_german" name="description_german"
                                                      class="form-control" style="height:300px;"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                          
                                <div class="col-md-6 mt-4">
                                    <div class="form-group">
                                    <button type="submit" class="btn btn-raised btn-primary waves-effect">Save</button>
                                      </div>
                                </div> 
                            </div>
                           
                        </form>
                    </div>
                </div>
            </div>
        </div> 
    </div>  
    
<script type="text/javascript">

    function PreviewImage() {
        var oFReader = new FileReader();
        oFReader.readAsDataURL(document.getElementById("uploadImage").files[0]);

        oFReader.onload = function (oFREvent) {
            document.getElementById("uploadPreview").src = oFREvent.target.result;
        };
    };

</script>

<script> 
    function onlyNumberKey(evt) { 
          
        // Only ASCII charactar in that range allowed 
        var ASCIICode = (evt.which) ? evt.which : evt.keyCode 
        if (ASCIICode > 31 && (ASCIICode < 48 || ASCIICode > 57)) 
            return false; 
        return true; 
    } 
</script> 

<script type="text/javascript">

    $( "#myform" ).validate({
        rules: {
            title_english: {
                required: true,
                minlength: 2,
                maxlength: 150
            },
            description_english: {
                required: true,
            },
            title_german: {
                required: true,
                minlength: 2,
                maxlength: 150
            },
            description_german: {
                required: true,
            },
        },
        messages: {
            title_english: {
                required: "Please provide german title",
            },
            description_english: {
                required: "Please provide german description",
            },
            title_german: {
                required: "Please provide german title",
            },
            description_german: {
                required: "Please provide german description",
            },
        }
    });
</script>
@endsection     

resources/views/admin/faqs/edit.blade.php
@extends('admin.layout')

@section('content')
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>Edit FAQs</h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="zmdi zmdi-home"></i> Home</a>
                    </li>
                    <li class="breadcrumb-item active">Edit FAQs</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    @if ($message = Session::get('success'))
                        <div class="alert bg-success text-white alert-styled-left alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                            <span class="font-weight-semibold">Well done!</span> {{$message}}.
                        </div>
                    @endif
                    <div class="header">
                        @if (count($errors) > 0)
                            <div class="alert alert-danger">
                                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <ul class="header-dropdown">

                            <a href="{{url('faqs')}}"><i class="zmdi zmdi-arrow-left"></i></a>
                        </ul>
                        <br>
                    </div>
                    <div class="body">
                        <form action="{{ route('faqs.update',$data->id) }}" id="myform" method="POST"
                              enctype="multipart/form-data" runat="server">
                            @csrf
                            @method('PUT')
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="title_english">Title English</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="title_english" name="title_english"
                                                   class="form-control" value="{{$data->title_english}}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="description_english">Detail English</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <textarea type="text" id="description_english" name="description_english"
                                                      class="form-control" value="{{$data->description_english}}"
                                                      style="height:200px;">{{$data->description_english}}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="title_german">Title German</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <input type="text" id="title_german" name="title_german"
                                                   class="form-control" value="{{$data->title_german}}">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <label for="description_german">Detail German</label>
                                    <div class="form-group">
                                        <div class="form-line">
                                            <textarea type="text" id="description_german" name="description_german"
                                                      class="form-control" value="{{$data->description_german}}"
                                                      style="height:200px;">{{$data->description_german}}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">

                                <div class="col-md-6 mt-4">
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-raised btn-primary waves-effect">Save
                                        </button>
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">

        function PreviewImage() {
            var oFReader = new FileReader();
            oFReader.readAsDataURL(document.getElementById("uploadImage").files[0]);

            oFReader.onload = function (oFREvent) {
                document.getElementById("uploadPreview").src = oFREvent.target.result;
            };
        };

    </script>

    <script>
        function onlyNumberKey(evt) {

            // Only ASCII charactar in that range allowed
            var ASCIICode = (evt.which) ? evt.which : evt.keyCode
            if (ASCIICode > 31 && (ASCIICode < 48 || ASCIICode > 57))
                return false;
            return true;
        }
    </script>

    <script type="text/javascript">

        $("#myform").validate({
            rules: {
                title_english: {
                    required: true,
                    minlength: 2,
                    maxlength: 150
                },
                description_english: {
                    required: true,
                },
                title_german: {
                    required: true,
                    minlength: 2,
                    maxlength: 150
                },
                description_german: {
                    required: true,
                },
            },
            messages: {
                title_english: {
                    required: "Please provide a title",
                },
                description_english: {
                    required: "Please provide a description",
                },
                title_german: {
                    required: "Please provide a title",
                },
                description_german: {
                    required: "Please provide a description",
                },
            }
        });
    </script>
@endsection     

resources/views/admin/faqs/index.blade.php
@extends('admin.layout')

@section('content')
<?php
$i = 1;
?>
    <div class="block-header">
        <div class="row">
            <div class="col-lg-7 col-md-6 col-sm-12">
                <h2>FAQs List
                </h2>
            </div>
            <div class="col-lg-5 col-md-6 col-sm-12">
                <ul class="breadcrumb float-md-right">
                    <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="zmdi zmdi-home"></i> Home</a></li>
                    <li class="breadcrumb-item active">FAQs List</li>
                </ul>
            </div>
        </div>
    </div>
   <!--  <button class="btn btn-raised btn-primary waves-effect" data-type="autoclose-timer">CLICK ME</button> -->
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                     @if ($message = Session::get('success'))
                      <div class="alert bg-success text-white alert-styled-left alert-dismissible">
                              <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                              <span class="font-weight-semibold">Well done!</span> {{$message}}.
                              </div>
                      @endif 
                       <div class="header">
                        <ul class="header-dropdown m-r--5">
                            <a href="{{route('faqs.create')}}" class="btn btn-raised btn-primary m-t-15 waves-effect">Add FAQs</a>
                        </ul><br>
                    </div>               
                    
                    <div class="body table-responsive">
                        <table class="table w-100 table-bordered table-hover js-basic-example " id="faqs_table">
                            <thead style="background-color:#ededed;">
                                <tr class="text-center">
                                    <th>ID</th>
                                    <th>Title English</th>
                                    <th>Descrtiption English</th>
                                    <th>ACTION</th>
                                </tr>
                            </thead>
                            
                            <tbody>
                           
                            </tbody>
                            
                        </table>
                    </div>
                </div>
            </div>
        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>  

 
    <script type="text/javascript">
        $(function () {
           var table = $('#faqs_table').DataTable({
                   processing: true,
                   serverSide: true,
                   responsive: true,
                   ajax: "{{ route('faqs.index') }}",
                   columns: [
                       {data: 'id', name: 'id'},
                       {data: 'title_english', name: 'title_english'},
                       {data: 'description_english', name: 'description_english'},
                       {data: 'action', name: 'action', orderable: false, searchable: false},
                   ]
               });

           /*     var deleteID;
                $('body').on('click', '#getDeleteId', function () {
                    deleteID = $(this).data('id');
                })
                $('#SubmitDeleteArticleForm').click(function (e) {
                    e.preventDefault();
                    var id = deleteID;
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        url: "delete_user/" + id,
                        method: 'GET',
                        success: function (result) {
                            // $('#DeleteArticleModal').hide();
                            // $('#DeleteArticleModal').modal('hide');
                            
                            window.location.href = "delete_success_message_user";
                            location.reload();
                            // $(".alert").hide();
                            // $(".notify_alert").click();
                        }
                    });
                });
*/

        });
    </script>
    
@endsection     